{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# NEMA 23 5010 Motor 30:1 reduction\n",
    "\n",
    "### 3D-printable housing and 30:1 reduction for a 5010 motor, in NEMA 23 space.\n",
    "\n",
    "A [ring ratio difference](https://www.youtube.com/watch?v=0WCPCJ3As8o) drive is used to provide the reduction in a compact space with beefy teeth that can be 3D printed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//==============================================================================\n",
    "// Import the CADBook library\n",
    "//==============================================================================\n",
    "import * as cad from './src/index.js';\n",
    "Error.stackTraceLimit = 100;\n",
    "\n",
    "//==============================================================================\n",
    "// Default props for displaying parts and sketches\n",
    "//==============================================================================\n",
    "\n",
    "const SHAPERPROPS: cad.ShaperProps = {\n",
    "  closeSnapDistance: 0.0001,\n",
    "  closeSnapProp: 0.01,\n",
    "  meshLinearTolerance: 0.05,\n",
    "  meshAngularTolerance: 2.5\n",
    "}\n",
    "const SVGPROPS: cad.SvgRenderProps = {\n",
    "  scale: 1.0,\n",
    "  pathStyle: {\n",
    "    stroke: 'black',\n",
    "    fill: 'none',\n",
    "    strokeWidth: 0.1\n",
    "  },\n",
    "  tagStyles: {\n",
    "    'cut': {\n",
    "      stroke: '#FF8080',\n",
    "      fill: 'none',\n",
    "      strokeWidth: 0.1\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "const display = await cad.getDisplay(SVGPROPS, SHAPERPROPS);\n",
    "const memos = await cad.getMemoizer(SHAPERPROPS);"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Major Dimensions and Positions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "const CENTER_DISTANCE = 13; // distance from main axis to planet axis\n",
    "const R1_TEETH = 29;\n",
    "const P1_TEETH = 10;\n",
    "const R2_TEETH = 30;\n",
    "const P2_TEETH = 10;\n",
    "// gear ratios\n",
    "const R1 = R1_TEETH / P1_TEETH;\n",
    "const R2 = R2_TEETH / P2_TEETH;\n",
    "\n",
    "console.log(`Reduction ratio: ${Math.round(1000*R2 / (R2 - R1))/1000}`);\n",
    "\n",
    "// My print settings are set to make all the outlines this much bigger, and leave holes unchanged.\n",
    "// That compensates for an extrusion effect that would otherwise make gear teeth too small.\n",
    "const C1 = 0.0;\n",
    "const C1D = 2*C1; // C1 applied to a diameter\n",
    "\n",
    "// In order to make holes the right size, they need to be enlarged by this amount.\n",
    "// We cannot use print settings to make holes bigger, because that would shrink the teeth on internal gears.\n",
    "const C2 = 0.1;\n",
    "const CD = 2*C2; // C2 applied to a diameter\n",
    "\n",
    "//==============================================================================\n",
    "// Planets\n",
    "//==============================================================================\n",
    "\n",
    "const PLANET_SHAFT_FIT = 3+C2; // Don't need C2D here, because it's not a hole\n",
    "const PLANET_CLEAR_D = 18;\n",
    "const PLANET_DZ = 5;\n",
    "const PLANET_COMPRESS = -0.15;\n",
    "const PLANET_BEARING_FIT = 7+CD;\n",
    "const PLANET_SHAFT_CLEAR = 4+CD;\n",
    "const PLANET_BEARING_DZ = 3;\n",
    "const PLANET_SPLIT_Z = 0;\n",
    "const PLANET_FRONT_Z = PLANET_SPLIT_Z + PLANET_DZ;\n",
    "const PLANET_BACK_Z = PLANET_SPLIT_Z - PLANET_DZ;\n",
    "\n",
    "//==============================================================================\n",
    "// Rotor\n",
    "//==============================================================================\n",
    "\n",
    "const ROTOR_SHAFT_FIT = 3+CD;\n",
    "const ROTOR_WALL_DZ = 3;\n",
    "const ROTOR_WALL_SLOT_DZ = 2;\n",
    "const ROTOR_GAP_DZ = 0.5;\n",
    "const ROTOR_BACK_WALL_Z = PLANET_BACK_Z - ROTOR_GAP_DZ;\n",
    "const ROTOR_BACK_Z = ROTOR_BACK_WALL_Z - ROTOR_WALL_DZ;\n",
    "const ROTOR_FRONT_WALL_Z = PLANET_FRONT_Z + ROTOR_GAP_DZ;\n",
    "const ROTOR_FRONT_Z = ROTOR_FRONT_WALL_Z + ROTOR_WALL_DZ;\n",
    "const ROTOR_MOTOR_SCREW_XY = 12/Math.sqrt(2);\n",
    "const ROTOR_MOTOR_SCREW_CLOSE = 3+CD;\n",
    "const ROTOR_MOTOR_SCREW_HEAD_CLEAR = 6+CD;\n",
    "const ROTOR_MOUNT_CLEAR_DZ = 5; // enough room to get the screws into the holes\n",
    "const ROTOR_MOUNT_PLATE_DZ = 4; // thickness of the mounting plate to the motor\n",
    "const ROTOR_MOUNT_BACK_Z = ROTOR_BACK_Z - ROTOR_MOUNT_CLEAR_DZ - ROTOR_MOUNT_PLATE_DZ;\n",
    "\n",
    "//==============================================================================\n",
    "// Output\n",
    "//==============================================================================\n",
    "\n",
    "const OUTPUT_HOLE_D = 51+C2;\n",
    "const OUTPUT_RING_D = OUTPUT_HOLE_D - 3.2 - C2;\n",
    "// center of bearing race\n",
    "const OUTPUT_RACE_D = (OUTPUT_RING_D + OUTPUT_HOLE_D) / 2;\n",
    "const OUTPUT_GEAR_BACK_Z = PLANET_SPLIT_Z + 1;\n",
    "const OUTPUT_GEAR_FRONT_Z = ROTOR_FRONT_Z + 1\n",
    "const OUTPUT_PLATE_DZ = 7;\n",
    "const OUTPUT_FRONT_Z = OUTPUT_GEAR_FRONT_Z + OUTPUT_PLATE_DZ;\n",
    "\n",
    "const OUTPUT_BALL_BEARING_D = 4.5;\n",
    "// center to corner for diamond-shaped bearing race\n",
    "const OUTPUT_RACE_C2C = OUTPUT_BALL_BEARING_D * Math.sqrt(2)/2; // about 3.2\n",
    "// center height of output race\n",
    "const OUTPUT_RACE_Z = OUTPUT_FRONT_Z - OUTPUT_PLATE_DZ*0.5;\n",
    "\n",
    "const OUTPUT_SHAFT_FIT = 5;\n",
    "const OUTPUT_SCREW_CIRCLE_D = 16;\n",
    "const OUTPUT_SCREW_PILOT = 2+CD;\n",
    "\n",
    "\n",
    "//==============================================================================\n",
    "// Housing\n",
    "//==============================================================================\n",
    "\n",
    "const NEMA23_OUTER_XY = 56.4;\n",
    "const NEMA23_BOLT_XY = 47.1;\n",
    "const NEMA23_BOLT_FIT = 5 + CD;\n",
    "const MOTOR_DZ = 19.6;\n",
    "const MOTOR_CLEAR_D = 58;\n",
    "const HOUSING_PLATE_DZ=6.5;\n",
    "\n",
    "const HOUSING_HOLE_FRONT_Z = OUTPUT_GEAR_FRONT_Z;\n",
    "const HOUSING_GEAR_FRONT_Z = PLANET_SPLIT_Z - 1;\n",
    "const HOUSING_GEAR_BACK_Z = ROTOR_BACK_Z-1;\n",
    "const HOUSING_PLATE_Z = ROTOR_MOUNT_BACK_Z - MOTOR_DZ;\n",
    "const HOUSING_BACK_Z = HOUSING_PLATE_Z - HOUSING_PLATE_DZ;\n",
    "\n",
    "console.log(`Total Height: ${OUTPUT_FRONT_Z - HOUSING_BACK_Z}`)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Main Sketches"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "//==============================================================================\n",
    "// Gear and Pinion Definitions\n",
    "//==============================================================================\n",
    "\n",
    "const R1Props: cad.GearPairProps = {\n",
    "  clearanceModPercent: 5,\n",
    "  gearTeeth: R1_TEETH,\n",
    "  pinionTeeth: P1_TEETH,\n",
    "  pressureAngle: 20,\n",
    "  profileShiftPercent: 15,\n",
    "  isInternalGear: true,\n",
    "  isMaxFillet: true,\n",
    "  filletToleranceModPercent: 0.5,\n",
    "  faceToleranceModPercent: 0.05,\n",
    "  size: CENTER_DISTANCE,\n",
    "  sizeType: 'centerDist'\n",
    "}\n",
    "\n",
    "const R2Props: cad.GearPairProps = {\n",
    "  ...R1Props,\n",
    "  gearTeeth: R2_TEETH,\n",
    "  pinionTeeth: P2_TEETH\n",
    "};\n",
    "\n",
    "// planet center points\n",
    "const PCw = [CENTER_DISTANCE, 0];\n",
    "const PCn = cad.ID2D.rotate(120).mapPoint(PCw[0], PCw[1]);\n",
    "const PCs = cad.ID2D.rotate(-120).mapPoint(PCw[0], PCw[1]);\n",
    "\n",
    "// rotation for planets to mesh with gears\n",
    "const ROTw1 = 0;\n",
    "const ROTn1 = 120 - 120 * R1;\n",
    "const ROTs1 = -ROTn1;\n",
    "\n",
    "const ROTw2 = 0;\n",
    "const ROTn2 = 120 - 120 * R2;\n",
    "const ROTs2 = -ROTn2;\n",
    "\n",
    "const HousingGears = cad.createGearPair(R1Props);\n",
    "const OutputGears = cad.createGearPair(R2Props);\n",
    "\n",
    "//==============================================================================\n",
    "// NEMA 23 plate and bolt holes\n",
    "//==============================================================================\n",
    "const Nema23 = (pen: cad.Pen2D) => {\n",
    "  const a = NEMA23_OUTER_XY / 2;\n",
    "  const b = NEMA23_BOLT_XY / 2;\n",
    "\n",
    "  pen.move(a, -b);\n",
    "  pen.line(a, b);\n",
    "  pen.arc(b, a, 90);\n",
    "  pen.line(-b, a);\n",
    "  pen.arc(-a, b, 90);\n",
    "  pen.line(-a, -b);\n",
    "  pen.arc(-b, -a, 90);\n",
    "  pen.line(b, -a);\n",
    "  pen.arc(a, -b, 90);\n",
    "\n",
    "  pen.circle(b, b, NEMA23_BOLT_FIT);\n",
    "  pen.circle(-b, b, NEMA23_BOLT_FIT);\n",
    "  pen.circle(-b, -b, NEMA23_BOLT_FIT);\n",
    "  pen.circle(b, -b, NEMA23_BOLT_FIT);\n",
    "}\n",
    "\n",
    "//==============================================================================\n",
    "// Carrier Design\n",
    "//==============================================================================\n",
    "\n",
    "const CARRIER_BRIDGE = 6;\n",
    "const CARRIER_BRIDGE_LEN = 8;\n",
    "const CARRIER_CENTER_D = 13.15;\n",
    "\n",
    "const carrierOutline = (pen: cad.Pen2D) => {\n",
    "  const p = cad.polar2D(pen);\n",
    "  const rbridge = CENTER_DISTANCE;\n",
    "  const bridgeh = rbridge + CARRIER_BRIDGE*0.35 + PLANET_COMPRESS;\n",
    "  for (let rot = 0; rot < 360; rot += 120) {\n",
    "    if (!rot) {\n",
    "      p.move(rot - 60, CARRIER_CENTER_D, 0);\n",
    "    }\n",
    "    p.conic(rot - 60, CARRIER_CENTER_D, 5, rot, bridgeh, -CARRIER_BRIDGE_LEN, .8);\n",
    "    p.line(rot, bridgeh, CARRIER_BRIDGE_LEN);\n",
    "    p.conic(rot + 60, CARRIER_CENTER_D, -5, rot + 60, CARRIER_CENTER_D, 0, .8);\n",
    "  }\n",
    "  pen.circle(0,0,ROTOR_SHAFT_FIT);\n",
    "}\n",
    "const rotorScrewClearHoles = (pen: cad.Pen2D) => {\n",
    "  for (let x=-1; x<=1; x+=2) for (let y=-1; y<=1; y+=2) {\n",
    "    pen.circle(x*ROTOR_MOTOR_SCREW_XY/2,y*ROTOR_MOTOR_SCREW_XY/2,ROTOR_MOTOR_SCREW_HEAD_CLEAR,'cut');\n",
    "  }\n",
    "}\n",
    "const rotorMountCloseSketch = (pen: cad.Pen2D) => {\n",
    "  pen.circle(0,0,CENTER_DISTANCE*2);\n",
    "  for (let x=-1; x<=1; x+=2) for (let y=-1; y<=1; y+=2) {\n",
    "    pen.circle(x*ROTOR_MOTOR_SCREW_XY/2,y*ROTOR_MOTOR_SCREW_XY/2,ROTOR_MOTOR_SCREW_CLOSE,'cut');\n",
    "  }\n",
    "  pen.circle(0,0,ROTOR_SHAFT_FIT);\n",
    "}\n",
    "const carrierShaftSupports = (pen: cad.Pen2D) => {\n",
    "  const p = cad.polar2D(pen);\n",
    "  const rshafts = CENTER_DISTANCE + PLANET_COMPRESS;\n",
    "  for (let rot = 0; rot < 360; rot += 120) {\n",
    "    p.move(rot, CENTER_DISTANCE + CARRIER_BRIDGE / 2, -PLANET_SHAFT_FIT / 2, 'cut');\n",
    "    p.line(rot, CENTER_DISTANCE + CARRIER_BRIDGE / 2, PLANET_SHAFT_FIT / 2);\n",
    "    p.line(rot, rshafts, PLANET_SHAFT_FIT / 2);\n",
    "    p.arc(rot, rshafts - PLANET_SHAFT_FIT / 2, 0, 90);\n",
    "    p.arc(rot, rshafts, -PLANET_SHAFT_FIT / 2, 90);\n",
    "    p.line(rot, CENTER_DISTANCE + CARRIER_BRIDGE / 2, -PLANET_SHAFT_FIT / 2);\n",
    "  }\n",
    "}\n",
    "const carrierPinionClearance = (pen: cad.Pen2D) => {\n",
    "  const p = cad.polar2D(pen);\n",
    "  for (let rot = 0; rot < 360; rot += 120) {\n",
    "    p.circle(rot, CENTER_DISTANCE, 0, PLANET_CLEAR_D, 'cut');\n",
    "  }\n",
    "  p.circle(0,0,0,ROTOR_MOTOR_SCREW_XY*Math.SQRT2+ROTOR_MOTOR_SCREW_HEAD_CLEAR+0.01, 'cut');\n",
    "}\n",
    "\n",
    "const carrierFullSketch = (pen: cad.Pen2D) => {\n",
    "  carrierOutline(pen);\n",
    "  carrierShaftSupports(pen);\n",
    "  carrierPinionClearance(pen);\n",
    "  rotorMountCloseSketch(pen);\n",
    "  rotorScrewClearHoles(pen);\n",
    "}\n",
    "\n",
    "\n",
    "//==============================================================================\n",
    "// Show the work\n",
    "//==============================================================================\n",
    "\n",
    "display.sketch((pen) => {\n",
    "  const L = cad.ID2D.translate(CENTER_DISTANCE * -2.2, 0);\n",
    "  const R = cad.ID2D.translate(CENTER_DISTANCE * 2.2, 0);\n",
    "\n",
    "  HousingGears.gear(L.mapPen(pen));\n",
    "  carrierFullSketch(L.mapPen(pen));\n",
    "  HousingGears.pinion(\n",
    "    L.translate(PCw[0], PCw[1]).rotate(ROTw1).mapPen(pen)\n",
    "  );\n",
    "  HousingGears.pinion(\n",
    "    L.translate(PCn[0], PCn[1]).rotate(ROTn1).mapPen(pen)\n",
    "  );\n",
    "  HousingGears.pinion(\n",
    "    L.translate(PCs[0], PCs[1]).rotate(ROTs1).mapPen(pen)\n",
    "  );\n",
    "  L.mapPen(pen).circle(0, 0, NEMA23_OUTER_XY);\n",
    "  L.mapPen(pen).circle(0, 0, OUTPUT_HOLE_D);\n",
    "  Nema23(L.mapPen(pen));\n",
    "  \n",
    "  OutputGears.gear(R.mapPen(pen));\n",
    "  carrierFullSketch(R.mapPen(pen));\n",
    "  OutputGears.pinion(\n",
    "    R.translate(PCw[0], PCw[1]).rotate(ROTw2).mapPen(pen)\n",
    "  );\n",
    "  OutputGears.pinion(\n",
    "    R.translate(PCn[0], PCn[1]).rotate(ROTn2).mapPen(pen)\n",
    "  );\n",
    "  OutputGears.pinion(\n",
    "    R.translate(PCs[0], PCs[1]).rotate(ROTs2).mapPen(pen)\n",
    "  );\n",
    "  R.mapPen(pen).circle(0, 0, OUTPUT_RING_D);\n",
    "});\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Inner Rotor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//==============================================================================\n",
    "// PLANET GEARS\n",
    "//==============================================================================\n",
    "\n",
    "const planet = (shaper: cad.Shaper3D, rot1: number, rot2: number) => {\n",
    "  const inSketch = cad.ID2D.rotate(rot1).mapSketch(HousingGears.pinion);\n",
    "  const outSketch = cad.ID2D.rotate(rot2).mapSketch(OutputGears.pinion);\n",
    "  const target = shaper.extrude(cad.TOPVIEW, inSketch, [0, 0, PLANET_BACK_Z], [0, 0, PLANET_SPLIT_Z]);\n",
    "  let tool = shaper.extrude(cad.TOPVIEW, outSketch, [0, 0, PLANET_SPLIT_Z], [0, 0, PLANET_FRONT_Z]);\n",
    "  shaper.join(target, tool);\n",
    "  let sketch: cad.Sketch = (pen: cad.Pen2D) => {\n",
    "    pen.circle(0, 0, PLANET_SHAFT_CLEAR);\n",
    "  }\n",
    "  tool = shaper.extrude(cad.TOPVIEW, sketch, [0, 0, -PLANET_DZ], [0, 0, PLANET_DZ]);\n",
    "  shaper.cut(target, tool);\n",
    "  sketch = (pen: cad.Pen2D) => {\n",
    "    pen.circle(0, 0, PLANET_BEARING_FIT);\n",
    "  }\n",
    "  tool = shaper.extrude(cad.TOPVIEW, sketch, [0, 0, PLANET_DZ - PLANET_BEARING_DZ], [0, 0, PLANET_DZ]);\n",
    "  shaper.cut(target, tool);\n",
    "  tool = shaper.extrude(cad.TOPVIEW, sketch, [0, 0, -PLANET_DZ + PLANET_BEARING_DZ], [0, 0, -PLANET_DZ]);\n",
    "  shaper.cut(target, tool);\n",
    "  return [\n",
    "    target\n",
    "  ];\n",
    "}\n",
    "\n",
    "// These cut operations take a long time, so memoizer the results\n",
    "const planetW = memos.part(\"planetW\", (shaper) => planet(shaper, ROTw1, ROTw2));\n",
    "const planetN = memos.part(\"planetN\", (shaper) => planet(shaper, ROTn1, ROTn2));\n",
    "const planetS = memos.part(\"planetS\", (shaper) => planet(shaper, ROTs1, ROTs2));\n",
    "\n",
    "display.part((shaper) => [\n",
    "  ...planetN(cad.ID3D.translate(-28, 0, 0).mapShaper(shaper)),\n",
    "  ...planetS(shaper),\n",
    "  ...planetW(cad.ID3D.translate(28, 0, 0).mapShaper(shaper)),\n",
    "], {\n",
    "  'STLB': 'planets.stl'\n",
    "});"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//==============================================================================\n",
    "// ROTOR\n",
    "//==============================================================================\n",
    "\n",
    "let rotor: cad.Part = (shaper) => {\n",
    "  const retid = shaper.extrude(cad.TOPVIEW, carrierOutline, [0, 0, ROTOR_BACK_Z], [0, 0, ROTOR_FRONT_Z]);\n",
    "  let tools = shaper.extrudeAll(cad.TOPVIEW, carrierPinionClearance, \n",
    "    [0, 0, ROTOR_BACK_WALL_Z], \n",
    "    [0, 0, ROTOR_FRONT_WALL_Z]);\n",
    "  shaper.cut(retid, tools);\n",
    "  tools = shaper.extrudeAll(cad.TOPVIEW, carrierShaftSupports, \n",
    "    [0, 0, ROTOR_BACK_WALL_Z - ROTOR_WALL_SLOT_DZ], \n",
    "    [0, 0, ROTOR_FRONT_WALL_Z + ROTOR_WALL_SLOT_DZ]);\n",
    "  shaper.cut(retid, tools);\n",
    "  const mountId = shaper.extrude(cad.TOPVIEW, rotorMountCloseSketch, [0,0,ROTOR_MOUNT_BACK_Z], [0,0,ROTOR_BACK_Z]);\n",
    "  shaper.join(retid, [mountId]);\n",
    "  tools = shaper.extrudeAll(cad.TOPVIEW, rotorScrewClearHoles, \n",
    "    [0, 0, ROTOR_MOUNT_BACK_Z + ROTOR_MOUNT_PLATE_DZ], \n",
    "    [0, 0, ROTOR_FRONT_Z + 1]);\n",
    "  shaper.cut(retid, tools);\n",
    "  return [retid];\n",
    "}\n",
    "rotor = memos.part('rotor', rotor);\n",
    "display.part(rotor, {\n",
    "  'STLB': 'rotor.stl'\n",
    "});"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Output Layer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "const BearingRaceSection = (pen: cad.Pen2D) => {\n",
    "  const cx = OUTPUT_RACE_D/2;\n",
    "  const a = OUTPUT_RACE_C2C\n",
    "  pen.move(cx+a,0);\n",
    "  pen.line(cx,a);\n",
    "  pen.line(cx-a,0);\n",
    "  pen.line(cx,-a);\n",
    "  pen.line(cx+a,0);\n",
    "}\n",
    "\n",
    "const BearingRaceCut: cad.Part = (shaper: cad.Shaper3D) : cad.BodyID[] => {\n",
    "  const id = shaper.revolve(cad.FRONTVIEW, BearingRaceSection, [0,0,OUTPUT_RACE_Z], 360);\n",
    "  return [id];\n",
    "}\n",
    "\n",
    "const HOUSING_JOIN_DZ=2;\n",
    "const HousingJoinSection = (pen: cad.Pen2D) => {\n",
    "  const ir = NEMA23_BOLT_FIT/2;\n",
    "  const d = HOUSING_JOIN_DZ;\n",
    "  pen.move(ir,-d);\n",
    "  pen.line(ir+d, 0);\n",
    "  pen.line(ir, d);\n",
    "  pen.line(ir,-d);\n",
    "}\n",
    "const HousingJoin = memos.part('HousingJoin', (shaper: cad.Shaper3D) : cad.BodyID[] => {\n",
    "  const id = shaper.revolve(cad.FRONTVIEW, HousingJoinSection, [0,0,0], 360);\n",
    "  return [id];\n",
    "});\n",
    "const ShapeHousingJoins = (shaper: cad.Shaper3D, z: number) : cad.BodyID[] => {\n",
    "  return ([[-1,-1], [-1,1], [1,-1], [1,1]] as [number,number][]).flatMap(([ix,iy]) => {\n",
    "    const xform = cad.ID3D.translate(ix*(NEMA23_BOLT_XY/2), iy*(NEMA23_BOLT_XY/2), z);\n",
    "    return HousingJoin(xform.mapShaper(shaper));\n",
    "  });\n",
    "}\n",
    "\n",
    "const OutputOuter = memos.part('OutputOuter', (shaper: cad.Shaper3D) : cad.BodyID[] => {\n",
    "  const id = shaper.extrude(cad.TOPVIEW, (pen) => {\n",
    "    Nema23(pen);\n",
    "    pen.circle(0,0,OUTPUT_HOLE_D);\n",
    "  }, [0,0,OUTPUT_GEAR_FRONT_Z], [0,0,OUTPUT_FRONT_Z]);\n",
    "  const raceIds = BearingRaceCut(shaper);\n",
    "  shaper.cut(id, raceIds);\n",
    "  shaper.join(id, ShapeHousingJoins(shaper, OUTPUT_GEAR_FRONT_Z));\n",
    "  return [id];\n",
    "});\n",
    "\n",
    "\n",
    "const OutputRotor = memos.part('OutputRotor', (shaper: cad.Shaper3D) : cad.BodyID[] => {\n",
    "  const id = shaper.extrude(cad.TOPVIEW, (pen) => {\n",
    "    pen.circle(0,0,OUTPUT_RING_D);\n",
    "  }, [0,0,OUTPUT_GEAR_BACK_Z], [0,0,OUTPUT_FRONT_Z]);\n",
    "  const raceIds = BearingRaceCut(shaper);\n",
    "  shaper.cut(id, raceIds);\n",
    "  const toolid = shaper.extrude(cad.TOPVIEW, OutputGears.gear,\n",
    "    [0,0,OUTPUT_GEAR_BACK_Z],\n",
    "    [0,0,OUTPUT_GEAR_FRONT_Z]);\n",
    "  shaper.cut(id, toolid);\n",
    "  const plateHoleIds = shaper.extrudeAll(cad.TOPVIEW, (pen) => {\n",
    "    pen.circle(0,0,OUTPUT_SHAFT_FIT);\n",
    "    let xform = cad.ID2D;\n",
    "    for (let i=0; i<4; i++) {\n",
    "      xform.mapPen(pen).circle(OUTPUT_SCREW_CIRCLE_D/2,0,OUTPUT_SCREW_PILOT);\n",
    "      xform = xform.rotate(90);\n",
    "    } \n",
    "  }, [0,0,OUTPUT_GEAR_FRONT_Z-0.5], [0,0,OUTPUT_FRONT_Z+0.5]);\n",
    "  shaper.cut(id, plateHoleIds);\n",
    "  return [id];\n",
    "});\n",
    "\n",
    "\n",
    "const raceHole = memos.part('raceHoles', (shaper: cad.Shaper3D) : cad.BodyID[] => {\n",
    "  const holeids = shaper.extrudeAll(cad.FRONTVIEW, (pen) => {\n",
    "    const d = (OUTPUT_BALL_BEARING_D + 0.5)/2;\n",
    "    pen.move(-d, OUTPUT_FRONT_Z+1);\n",
    "    pen.line(-d, OUTPUT_RACE_Z);\n",
    "    pen.arc(0, OUTPUT_RACE_Z-d, 90);\n",
    "    pen.arc(d, OUTPUT_RACE_Z, 90);\n",
    "    pen.line(d, OUTPUT_FRONT_Z+1);\n",
    "    pen.line(-d, OUTPUT_FRONT_Z+1);\n",
    "  }, [0,OUTPUT_RACE_D/2-2, 0], [0,OUTPUT_RACE_D/2+2, 0]);\n",
    "  return holeids;\n",
    "});\n",
    "\n",
    "const OutputRaceGuard = memos.part('OutputRaceGuard', (shaper: cad.Shaper3D) : cad.BodyID[] => {  \n",
    "  const id = shaper.extrude(cad.TOPVIEW, (pen) => {\n",
    "    pen.circle(0,0,OUTPUT_RACE_D + 1);\n",
    "    pen.circle(0,0,OUTPUT_RACE_D - 1);\n",
    "  }, [0,0,PLANET_SPLIT_Z], [0,0,OUTPUT_FRONT_Z-0.5]);\n",
    "\n",
    "  const N = 12;\n",
    "  for (let i=0; i<N; i++) {\n",
    "    const rot = cad.ID3D.rotateTop(i*360/N);\n",
    "    shaper.cut(id, raceHole(rot.mapShaper(shaper)));\n",
    "  }\n",
    "  return [id];\n",
    "});\n",
    "\n",
    "display.part((shaper) => [\n",
    "  ...OutputOuter(shaper),\n",
    "  ...OutputRotor(shaper),\n",
    "], {\n",
    "  'STLB': 'outputlayer.stl'\n",
    "});\n",
    "display.part(OutputRaceGuard, {\n",
    "  'STLB': 'raceguard.stl'\n",
    "});\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Housing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//==============================================================================\n",
    "// HOUSING STATOR\n",
    "//==============================================================================\n",
    "\n",
    "let housing : cad.Part = (shaper: cad.Shaper3D) => {\n",
    "  // start with extruded NEMA23 outline\n",
    "  const partid = shaper.extrude(cad.TOPVIEW, Nema23, [0,0,HOUSING_GEAR_BACK_Z], [0,0,HOUSING_HOLE_FRONT_Z]);\n",
    "  // cut out output hole\n",
    "  let toolid = shaper.extrude(cad.TOPVIEW, ((pen: cad.Pen2D) => pen.circle(0,0, OUTPUT_HOLE_D)),\n",
    "    [0,0,HOUSING_GEAR_FRONT_Z],\n",
    "    [0,0,HOUSING_HOLE_FRONT_Z+1]);\n",
    "  shaper.cut(partid, toolid);\n",
    "  // cut out gear\n",
    "  toolid = shaper.extrude(cad.TOPVIEW, HousingGears.gear,\n",
    "    [0,0,HOUSING_GEAR_BACK_Z],\n",
    "    [0,0,HOUSING_GEAR_FRONT_Z+1]);\n",
    "  shaper.cut(partid, toolid);\n",
    "  shaper.cut(partid, ShapeHousingJoins(shaper, HOUSING_GEAR_BACK_Z));\n",
    "  shaper.cut(partid, ShapeHousingJoins(shaper, HOUSING_HOLE_FRONT_Z));\n",
    "  return [partid];\n",
    "}\n",
    "housing = memos.part(\"housing\", housing);\n",
    "display.part(housing, {\n",
    "  'STLB': 'housing.stl'\n",
    "});"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "//==============================================================================\n",
    "// HOUSING MOTOR CAGE\n",
    "//==============================================================================\n",
    "\n",
    "let housing : cad.Part = (shaper: cad.Shaper3D) => {\n",
    "  // start with extruded NEMA23 outline\n",
    "  const partid = shaper.extrude(cad.TOPVIEW, Nema23, [0,0,HOUSING_BACK_Z], [0,0,HOUSING_GEAR_BACK_Z]);\n",
    "  shaper.join(partid, ShapeHousingJoins(shaper, HOUSING_GEAR_BACK_Z));\n",
    "  // cut out motor clearance\n",
    "  let toolids = shaper.extrudeAll(cad.TOPVIEW, ((pen: cad.Pen2D) => {\n",
    "    pen.circle(0,0, MOTOR_CLEAR_D);\n",
    "    const dh = NEMA23_OUTER_XY + 1;\n",
    "    const dl = NEMA23_OUTER_XY/4;\n",
    "    pen.move(dh,dl);\n",
    "    pen.line(dl,dl);\n",
    "    pen.line(dl,dh);\n",
    "    pen.line(-dl,dh);\n",
    "    pen.line(-dl, dl);\n",
    "    pen.line(-dh,dl);\n",
    "    pen.line(-dh,-dl);\n",
    "    pen.line(-dl,-dl);\n",
    "    pen.line(-dl,-dh);\n",
    "    pen.line(dl,-dh);\n",
    "    pen.line(dl,-dl);\n",
    "    pen.line(dh,-dl);\n",
    "    pen.line(dh,dl);\n",
    "  }), \n",
    "    [0,0,HOUSING_PLATE_Z],\n",
    "    [0,0,HOUSING_GEAR_BACK_Z+10]);\n",
    "  shaper.cut(partid, toolids);\n",
    "\n",
    "  //1510 motor mounting holes\n",
    "  const screw_cs = [[8,0],[0,9.5],[-8,0],[0,-9.5]];\n",
    "  toolids = shaper.extrudeAll(cad.TOPVIEW, ((pen: cad.Pen2D) => {\n",
    "    pen.circle(0,0, 10);\n",
    "    for (const [cx,cy] of screw_cs) {\n",
    "      pen.circle(cx, cy, ROTOR_MOTOR_SCREW_CLOSE);\n",
    "    }\n",
    "  }), \n",
    "    [0,0,HOUSING_BACK_Z-1],\n",
    "    [0,0,HOUSING_PLATE_Z+1]);\n",
    "  shaper.cut(partid, toolids);\n",
    "  toolids = shaper.extrudeAll(cad.TOPVIEW, ((pen: cad.Pen2D) => {\n",
    "    for (const [cx,cy] of screw_cs) {\n",
    "      pen.circle(cx, cy, ROTOR_MOTOR_SCREW_HEAD_CLEAR);\n",
    "    }\n",
    "  }), \n",
    "    [0,0,HOUSING_BACK_Z-1],\n",
    "    [0,0,HOUSING_BACK_Z+HOUSING_PLATE_DZ/2]);\n",
    "  shaper.cut(partid, toolids);\n",
    "  return [partid];\n",
    "}\n",
    "housing = memos.part(\"cage\", housing);\n",
    "display.part(housing, {\n",
    "  'STLB': 'cage.stl'\n",
    "});"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "TypeScript",
   "language": "typescript",
   "name": "tslab"
  },
  "language_info": {
   "codemirror_mode": {
    "mode": "typescript",
    "name": "javascript",
    "typescript": true
   },
   "file_extension": ".ts",
   "mimetype": "text/typescript",
   "name": "typescript",
   "version": "3.7.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
